---

services:
  baikal:
    image: ghcr.io/teeuwen/baikal:${BAIKAL_VERSION}
    build:
      context: ./baikal
      args:
        BUILDKIT_DOCKERFILE_CHECK: ${BUILDKIT_DOCKERFILE_CHECK}
        BAIKAL_VERSION: ${BAIKAL_VERSION}

  postfix:
    image: ghcr.io/teeuwen/postfix:${POSTFIX_VERSION}
    build:
      context: ./postfix
      args:
        BUILDKIT_DOCKERFILE_CHECK: ${BUILDKIT_DOCKERFILE_CHECK}
        POSTFIX_VERSION: ${POSTFIX_VERSION}
