---

x-buildkit-config: &buildkit_config
  BUILDKIT_DOCKERFILE_CHECK: error=true;skip=InvalidDefaultArgInFrom

services:
  baikal:
    image: ghcr.io/teeuwen/baikal:${BAIKAL_VERSION}
    build:
      context: ./baikal
      args:
        <<: *buildkit_config
        BAIKAL_VERSION: ${BAIKAL_VERSION}

  postfix:
    image: ghcr.io/teeuwen/postfix:${POSTFIX_VERSION}
    build:
      context: ./postfix
      args:
        <<: *buildkit_config
        POSTFIX_VERSION: ${POSTFIX_VERSION}
