---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Linting
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
