---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      modifiedImages: ${{ steps.modified.outputs.images }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 25

      - id: modified
        name: Get modified images
        run: |
          PREV_SHA='${{ github.event.before }}'

          # If the previous SHA does not exist, we likely did a force push
          # In that case, we will mark all images as changed
          if git cat-file -e ${PREV_SHA}; then
            IMAGES=$(git diff --name-only ${PREV_SHA} HEAD | sed -n 's,^\([^./][^/]*\)/.*,\1,p' | uniq | jq -R . | jq -sc .)
          else
            IMAGES=$(ls -d */ | sed 's/.$//' | jq -R . | jq -sc .)
          fi

          echo "images=${IMAGES}" >> ${GITHUB_OUTPUT}

  release:
    name: Build and push
    needs: [prepare]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image: ['${{ fromJson(needs.prepare.outputs.modifiedImages) }}']
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.image }}
        run: |
          cd ${{ matrix.image }} && docker buildx bake \
            --push \
            --provenance=false \
            --sbom=false
